[env]
USER="root"
ROCKET_ADDRESS="0.0.0.0"
ROCKET_ENV="development"
ADDRESS="0.0.0.0:8002"
RUST_LOG="debug"
PG_DBNAME="postgres"
PG_HOST="localhost"
PG_PORT="5434"
PG_USER="postgres"
PG_PASSWORD="<your_pass>"
RUST_BACKTRACE="1"
PRIMARY="false"
ID="2"

SOCKET_PORT="8007"
SUCCESSOR_PORT="8006"
PREDECESSOR_PORT="8008"