[env]
USER="root"
ROCKET_ADDRESS="0.0.0.0"
ROCKET_ENV="development"
ADDRESS="0.0.0.0:8001"
RUST_LOG="debug"
PG_DBNAME="postgres"
PG_HOST="localhost"
PG_PORT="5433"
PG_USER="postgres"
PG_PASSWORD="<your_pass>"
RUST_BACKTRACE="1"

PRIMARY="false"
ID="1"
CONNECTIONS_FILE="../process_connections.json"