[env]
USER="root"
ROCKET_ADDRESS="0.0.0.0"
ROCKET_ENV="development"
ADDRESS="0.0.0.0:8003"
RUST_LOG="debug"
PG_DBNAME="postgres"
PG_HOST="localhost"
PG_PORT="5435"
PG_USER="postgres"
PG_PASSWORD="<your_pass>"
RUST_BACKTRACE="1"
PRIMARY="false"
ID="3"

SOCKET_PORT="8008"
SUCCESSOR_PORT="8007"
PREDECESSOR_PORT="8008"