[env]
USER = "root"
ROCKET_ADDRESS = "0.0.0.0"
ROCKET_ENV = "development"
ADDRESS = "0.0.0.0:8000"
RUST_LOG = "debug"
PG_DBNAME = "postgres"
PG_HOST = "localhost"
PG_PORT = "5432"
PG_USER = "postgres"
PG_PASSWORD = "<pass>"
RUST_BACKTRACE = "1"
